# -*- coding: utf-8 -*-
"""deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uaeVWxIrpTCtQMWQRdD4EonF91pUmUXi
"""

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

from sklearn.datasets import load_boston

df=load_boston()

df

df.keys()

dataset=pd.DataFrame(df.data,columns=df.feature_names)

dataset.head()

dataset["Price"]=df.target

dataset.info()

dataset.isnull().sum()

dataset.corr()

import seaborn as sns
sns.pairplot(dataset)

plt.scatter(dataset["CRIM"],dataset["Price"])
plt.xlabel("crime rate")
plt.ylabel("price")

sns.regplot(x="RM",y="Price",data=dataset)

X=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)

X_test=scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

lreg=LinearRegression()
lreg.fit(X_train,y_train)

print(lreg.coef_)

print(lreg.intercept_)

reg_pred=lreg.predict(X_test)

plt.scatter(y_test,reg_pred)

residuals=y_test-reg_pred

sns.displot(residuals,kind="kde")

from sklearn.metrics import r2_score
r2=r2_score(y_test,reg_pred)

r2

x0=dataset.head(0)

lreg.predict(scaler.transform(df.data[0].reshape(1,-1)))

df.target[0]

#pickle my model
import pickle
pickle.dump(lreg,open("lreg.pkl","wb"))

#if you would like to load it
pickled_model=pickle.load(open("lreg.pkl","rb"))

pickled_model.predict(scaler.transform(df.data[0].reshape(1,-1)))

